-- 01_schema.sql  
CREATE TABLE regions (
  region_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name   VARCHAR2(80) NOT NULL,
  phone       VARCHAR2(20),
  region_id   NUMBER NOT NULL,
  created_at  DATE DEFAULT SYSDATE,
  CONSTRAINT fk_customers_region
    FOREIGN KEY (region_id) REFERENCES regions(region_id)
);

-- products are stocked/managed by a region (warehouse/branch)
CREATE TABLE products (
  product_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name VARCHAR2(80) NOT NULL,
  category     VARCHAR2(40),
  unit_price   NUMBER(10,2) NOT NULL,
  region_id    NUMBER NOT NULL,
  is_active    CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y','N')),
  CONSTRAINT fk_products_region
    FOREIGN KEY (region_id) REFERENCES regions(region_id)
);

CREATE TABLE orders (
  order_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  order_date  DATE DEFAULT SYSDATE,
  status      VARCHAR2(20) DEFAULT 'PAID',
  CONSTRAINT fk_orders_customer
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
  order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      NUMBER NOT NULL,
  product_id    NUMBER NOT NULL,
  quantity      NUMBER NOT NULL CHECK (quantity > 0),
  unit_price    NUMBER(10,2) NOT NULL,
  CONSTRAINT fk_items_order
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
  CONSTRAINT fk_items_product
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);
